"""
GitGrade Data Contracts (Pydantic Schemas)

This is the "Constitution" of the project - all data flows through these models.
Aligned with the LLM output format in prompts/gitgrade_persona.md
"""

from pydantic import BaseModel, Field, HttpUrl
from typing import List, Optional, Literal, Dict

# --- INPUT SCHEMAS ---

class GradeRequest(BaseModel):
    """Request body for the /grade endpoint"""
    repo_url: str = Field(description="GitHub repository URL", examples=["https://github.com/user/repo"])
    deployed_link: Optional[str] = Field(default=None, description="Optional deployed link to verify")
    # Advanced Options
    mode: Literal["fast", "deep"] = Field(default="fast", description="Analysis depth: fast (30s) or deep (2-5min)")
    persona: Literal["recruiter", "mentor", "bug_hunter", "gsoc_admin"] = Field(
        default="mentor", 
        description="Viewer persona: changes the analysis focus and tone"
    )


# --- SUB-COMPONENTS (from LLM output) ---

class RoadmapItem(BaseModel):
    """A single actionable improvement step - with specific commands!"""
    step: str = Field(..., description="Short title like 'Add Unit Tests'")
    description: str = Field(..., description="SPECIFIC commands and files to create/modify")
    priority: Literal["Critical", "High", "Medium", "Low"]
    impact: Optional[str] = Field(None, description="What this fixes for employability")


class Metrics(BaseModel):
    """Hard metrics ratings - now includes commit quality and employability"""
    structure_rating: Literal["A", "B", "C", "D", "F"] = Field(..., description="Project organization score")
    docs_rating: Literal["A", "B", "C", "D", "F"] = Field(..., description="Documentation quality score")
    test_rating: Literal["A", "B", "C", "D", "F"] = Field(..., description="Test coverage score")
    commit_rating: Optional[Literal["A", "B", "C", "D", "F"]] = Field(None, description="Commit message quality")
    employability_score: Optional[int] = Field(None, ge=0, le=100, description="How likely to get hired based on this repo")


# --- NEW: FILE DIAGRAM & ASSETS ---

class FileNode(BaseModel):
    """A file/folder node for the interactive code diagram"""
    name: str = Field(..., description="File or folder name")
    path: str = Field(..., description="Full path from repo root")
    type: Literal["file", "folder"] = Field(..., description="Node type")
    health: Literal["healthy", "warning", "critical"] = Field("healthy", description="Health status for coloring")
    issues: List[str] = Field(default_factory=list, description="List of issues with this file")


class Asset(BaseModel):
    """A media asset found in the repository"""
    name: str = Field(..., description="File name")
    url: str = Field(..., description="Raw GitHub URL for direct access")
    type: Literal["image", "video", "other"] = Field(..., description="Asset type")
    path: str = Field(..., description="Path in repository")


# --- CORE OUTPUT (matches gitgrade_persona.md JSON schema) ---

class GradeReport(BaseModel):
    """
    The Master Object that the Frontend receives.
    This schema MUST match the JSON output defined in prompts/gitgrade_persona.md
    
    This is NOT a linter report. This is a RECRUITER SIMULATION.
    """
    # Identity (added by orchestrator)
    repo_name: str = Field(..., description="Repository name")
    owner: str = Field(..., description="Repository owner")
    
    # The Big Number
    score: int = Field(..., ge=0, le=100, description="0-100 Employability Score")
    level: Literal["Beginner", "Intermediate", "Advanced"] = Field(..., description="Skill tier")
    
    # NEW: Punchy headline
    headline: Optional[str] = Field(None, description="5-7 word 'newspaper headline' about this repo")
    
    # The 'Soft' Analysis (Generated by AI - Recruiter Voice)
    summary: str = Field(..., description="2-3 sentences like a recruiter's internal notes")
    critique_tone: str = Field(..., description="Witty one-liner roast or praise")
    
    # NEW: Recruiter Verdict
    recruiter_verdict: Optional[str] = Field(None, description="Strong Hire/Hire/Lean Hire/etc with justification")
    
    # Resume & Interview
    resume_bullets: List[str] = Field(..., min_length=1, max_length=5, description="CV bullet points")
    interview_question: str = Field(..., description="Technical question based on THEIR code")
    
    # NEW: Red/Green Flags (The Kill Sheet)
    red_flags: Optional[List[str]] = Field(default_factory=list, description="Issues that would make a recruiter hesitate")
    green_flags: Optional[List[str]] = Field(default_factory=list, description="Positive signals that impress recruiters")
    
    # Hard Metrics
    metrics: Metrics
    
    # Actionable Roadmap (The #1 Differentiator - Action over Data)
    roadmap: List[RoadmapItem] = Field(..., min_length=1, max_length=7, description="Step-by-step tutorial, not just data")
    
    # Deployment Status
    deployed_link: Optional[str] = Field(None, description="Verified deployment URL")
    deployment_status: Literal["live", "broken", "unknown"] = Field("unknown", description="Deployment verification result")
    
    # Interactive Code Diagram (Visual Proof - Red/Green Node Map)
    file_diagram: List[FileNode] = Field(default_factory=list, description="Files with health status for diagram")
    
    # Asset Gallery
    assets: List[Asset] = Field(default_factory=list, description="Media assets for gallery view")
    
    # Analysis Metadata (for frontend display)
    persona_used: Optional[str] = Field(None, description="The persona that analyzed this repo")
    analysis_mode: Optional[Literal["fast", "deep"]] = Field(None, description="Analysis mode used")


# --- INTERNAL DATA TRANSFER OBJECTS ---

class RepoMetadata(BaseModel):
    """Data scraped from GitHub (Stage 1 output)"""
    owner: str
    repo_name: str
    file_tree: str
    readme_content: str
    dependency_files: str
    commit_log: str
    detected_language: Optional[str] = None
    total_files: int = 0
    has_tests: bool = False
    has_readme: bool = False
    has_gitignore: bool = False
    # NEW: Additional data for features
    homepage_url: Optional[str] = None  # From GitHub API
    assets: List[Asset] = Field(default_factory=list)  # Media files found
    file_nodes: List[FileNode] = Field(default_factory=list)  # For diagram
    default_branch: str = "main"  # For raw URL construction
    # Optional additional repository statistics (may be empty if scraper didn't fetch)
    stars: int = 0
    forks: int = 0
    watchers: int = 0
    contributors: int = 0
    # Attach computed hard metrics (populated by orchestrator)
    hard_metrics: Optional["HardMetrics"] = None


class HardMetrics(BaseModel):
    """Calculated metrics from code analysis (Stage 2 output)"""
    structure_score: int = Field(..., ge=0, le=100)
    docs_score: int = Field(..., ge=0, le=100)
    test_score: int = Field(..., ge=0, le=100)
    commit_quality_score: int = Field(..., ge=0, le=100)
    issues: List[str] = Field(default_factory=list, description="List of detected issues")
